name       : ed9
model      : weights.pt
seed       : 0
gpu_number : "2"
# load existing weights from ./models/[name]/[model]
load       : False

# model

# nb of multi-head (n), nb of heads per multi-head (h)
dim      : [8, 8]
# embedding dimensions
emb      : [512,]
# use uncertainty quantification
vdp      : False
# Residual connection mode: identity, independence, taylor
residual : identity

# dataset

path        : ./data/20200718_C_NEW.feather
# proportion of test examples among all available examples
split_ratio : 0.1
# input sequence length
T_in        : 280
# output sequence length
T_out       : 40
# nb of longitude steps
nb_lon      : 50
# nb of latitude steps
nb_lat      : 50
# nb of altitude steps
nb_alt      : 5
# nb of classes
nb_classes  : 5
# aircraft state dimension
state_dim   : 6
# max nb of simultaneous aircraft
max_ac      : 785
# weights for balance
weights     : [1., 15., 15., 15., 15.]

# Hot-spot congestion prediction

predict_spot : False
# hot-spot int_lon, int_lat, int_alt
spot         : [42, 17, 3]

# training

batch_size    : 64
optimizer     : adam
learning_rate : 0.001
l2_reg        : 0.0
# parameter 'gamma' in focal loss
focus         : 3
# balance each batch by removing elements from class 0
balance       : True
epochs        : 1000
# test loss increase for early stopping
stop          : 0.5
# nb of workers for dataloaders
workers       : 8
# gradient clipping
clip          : 10
# probability clipping to avoid log(0)
tol           : 0.000001

