name       : ed10
model      : weights.pt
seed       : 42
gpu_number : "2"
# load existing weights from ./models/[name]/[model]
load       : False
pretrained : False
pretrain   : pretrain.pt  # ed9.pt

# plot

# Average variance (True) or only the last variance (False)
average   : True
# Variance scale range
var_range : null  # [0, 1]

# model

# nb of multi-head (n), nb of heads per multi-head (h)
dim      : [4, 4]
# embedding dimensions
emb      : [64,]
# use uncertainty quantification
vdp      : False
# Residual connection mode: identity, independence, taylor
residual : independence

# training

batch_size    : 64
optimizer     : adam
learning_rate : 1.e-2
# Nb of epochs between each restart for cosine annealing
Tmax          : 10
l2_reg        : 0.
# l2 regularization hyperparameter in ELBO
kl_factor     : 1.e-8
# parameter 'gamma' in focal loss
focus         : 2
# balance each batch by removing elements from class 0
balance       : True
# No class 0
no_zero       : True
epochs        : 50
# test loss increase for early stopping
stop          : 3
# nb of workers for dataloaders
workers       : 8
# gradient clipping
clip          : 10
# probability clipping to avoid log(0)
tol           : 1.e-6
# initialization factor for variance
var_init      : 1.e-6

# dataset

dataset     : pirats
path        : ./data/20200718_C_CONV.feather  # ./data/20200718_C_CONV.feather # ./data/20200718_C_NEW.feather
# proportion of test examples among all available examples
split_ratio : 0.1
# input sequence length
T_in        : 280
# output sequence length
T_out       : 40
# nb of longitude steps
nb_lon      : 50
# nb of latitude steps
nb_lat      : 50
# nb of altitude steps
nb_alt      : 5
# nb of classes
nb_classes  : 3
# aircraft state dimension
state_dim   : 6
# max nb of simultaneous aircraft
max_ac      : 674
# weights for balance
weights     : [1., 18.66, 18.66]

# Hot-spot congestion prediction

predict_spot : False
# hot-spot int_lon, int_lat, int_alt
spot         : [42, 17, 3]

