name       : vdp1
model      : weights.pt
seed       : 0
gpu_number : null
# load existing weights from ./models/[name]/[model]
load       : False

# model

# nb of multi-head (n), nb of heads per multi-head (h)
dim : [2, 2]
# embedding dimensions
emb : [64,]
# use uncertainty quantification
vdp : True

# dataset

path        : ./data/20200718_C_NEW.feather
# proportion of test examples among all available examples
split_ratio : 0.1
# input sequence length
T_in        : 160
# output sequence length
T_out       : 160
# nb of longitude steps
nb_lon      : 50
# nb of latitude steps
nb_lat      : 50
# nb of altitude steps
nb_alt      : 5
# nb of classes
nb_classes  : 5
# aircraft state dimension
state_dim   : 6
# max nb of simultaneous aircraft
max_ac      : 785

# Hot-spot congestion prediction

predict_spot : False
# hot-spot int_lon, int_lat, int_alt
spot         : [42, 17, 3]

# training

batch_size    : 64
optimizer     : adam
learning_rate : 0.001
l2_reg        : 0.0
epochs        : 100
# nb of workers for dataloaders
workers       : 8
# gradient clipping
clip          : 10
# test loss increase for early stopping
stop          : 1.1
# probability clipping to avoid log(0)
tol           : 0.000001

