name      : vdp43_5
# Variance scale range
var_range : null
window    : 10
plot_hist : True

# model

vdp      : True

# training

# l2 regularization hyperparameter in ELBO
kl_factor     : 1.e-10
epochs        : 5

# dataset

dataset      : pirats
nb_classes   : 4
no_zero      : False
predict_spot : False
