name      : vdp17
# Variance scale range
var_range : null

# model

vdp      : True

# training

# l2 regularization hyperparameter in ELBO
kl_factor     : 1.e-7
epochs        : 24

# dataset

# nb of classes
nb_classes   : 3
predict_spot : False
