name      : vdp37
# Variance scale range
var_range : null
window    : 100
plot_hist : True

# model

vdp      : True

# training

# l2 regularization hyperparameter in ELBO
kl_factor     : 1.e-10
epochs        : 5

# dataset

dataset      : pirats
nb_classes   : 3
no_zero      : True
predict_spot : False
