name       : ec1
model      : weights.pt
seed       : 0
gpu_number : null
load       : True

# model

# n, h
dim : [2, 2]

# dataset

path        : ./data/20200718_C_NEW.feather
split_ratio : 0.1
T_in        : 160
T_out       : 160
nb_lon      : 50
nb_lat      : 50
nb_classes  : 5
state_dim   : 6
max_ac      : 785

# training

batch_size    : 32
optimizer     : adam
learning_rate : 0.001
epochs        : 50
clip          : 10
weight        : 10
tol           : 0.000001

