name       : transfo2
model      : weights.pt
seed       : 0
gpu_number : null
load       : False

# model

# N, h, n, l
# N: nb of multi-heads
# h: nb of heads per multi-head
# n: dimension of query and key
# l: dimension of value
dim      : [6, 8, 128, 256]
channels : [4710, 4096, 2048, 1024, 1024, 2048, 2500]

# dataset

path        : ./data/20200718_C_NEW.feather
split_ratio : 0.1
T_in        : 160
T_out       : 160
nb_lon      : 50
nb_lat      : 50
nb_classes  : 5

# training

batch_size    : 64
optimizer     : adam
learning_rate : 0.001
epochs        : 50
